export type SkinCategory = "plinkoBall" | "cardBack" | "rouletteBall" | "rocketShip";

export type SkinRarity = "common" | "rare" | "epic" | "legendary";

export type ShopItem = {
  id: string;
  category: SkinCategory;
  name: string;
  description: string;
  price: number;
  preview: string;
  rarity: SkinRarity;
  source?: "shop" | "special";
};

export const SKIN_PRICES_BY_RARITY: Record<SkinRarity, number> = {
  common: 200,
  rare: 400,
  epic: 700,
  legendary: 1000,
};

export type EquippedSkins = Record<SkinCategory, string>;

export const DEFAULT_EQUIPPED_SKINS: EquippedSkins = {
  plinkoBall: "plinko-gold",
  cardBack: "cards-emerald",
  rouletteBall: "roulette-ivory",
  rocketShip: "rocket-classic",
};

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: "plinko-gold",
    category: "plinkoBall",
    name: "Bille or",
    description: "Classique lumineuse pour le Plinko.",
    price: 0,
    preview: "#ffd166",
    rarity: "common",
  },
  {
    id: "plinko-neon",
    category: "plinkoBall",
    name: "Bille neon",
    description: "Vert arcade, tres visible dans la grille.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#79e29f",
    rarity: "common",
  },
  {
    id: "plinko-ruby",
    category: "plinkoBall",
    name: "Bille rubis",
    description: "Rouge profond avec halo chaud.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#ff6b6b",
    rarity: "rare",
  },
  {
    id: "plinko-ocean",
    category: "plinkoBall",
    name: "Bille ocean",
    description: "Bleu vif, lisible meme sur les collisions rapides.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#5eb8f1",
    rarity: "rare",
  },
  {
    id: "plinko-lilac",
    category: "plinkoBall",
    name: "Bille lilas",
    description: "Teinte douce avec un halo plus froid.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#c58cff",
    rarity: "epic",
  },
  {
    id: "plinko-mint",
    category: "plinkoBall",
    name: "Bille menthe",
    description: "Vert clair satine pour varier du neon.",
    price: SKIN_PRICES_BY_RARITY.legendary,
    preview: "#9cf3d3",
    rarity: "legendary",
  },
  {
    id: "plinko-cloud",
    category: "plinkoBall",
    name: "Bille nuage",
    description: "Blanc bleute doux avec reflet leger.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#d8f3ff",
    rarity: "common",
  },
  {
    id: "plinko-amber",
    category: "plinkoBall",
    name: "Bille ambre",
    description: "Orange clair lisible dans le plateau.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#f5a95b",
    rarity: "common",
  },
  {
    id: "plinko-emerald",
    category: "plinkoBall",
    name: "Bille emeraude",
    description: "Vert profond avec halo net.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#34c98b",
    rarity: "rare",
  },
  {
    id: "plinko-storm",
    category: "plinkoBall",
    name: "Bille tempete",
    description: "Bleu gris electrique pour les rebonds rapides.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#6f8cff",
    rarity: "epic",
  },
  {
    id: "cards-emerald",
    category: "cardBack",
    name: "Dos emeraude",
    description: "Motif casino sobre pour le blackjack.",
    price: 0,
    preview: "#2f5f53",
    rarity: "common",
  },
  {
    id: "cards-midnight",
    category: "cardBack",
    name: "Dos minuit",
    description: "Bleu nuit avec grille fine.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#263a80",
    rarity: "common",
  },
  {
    id: "cards-royal",
    category: "cardBack",
    name: "Dos royal",
    description: "Violet sombre et accents dores.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#6541a5",
    rarity: "rare",
  },
  {
    id: "cards-sunset",
    category: "cardBack",
    name: "Dos couchant",
    description: "Rouge ambre avec des lignes plus chaudes.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#d86642",
    rarity: "epic",
  },
  {
    id: "cards-obsidian",
    category: "cardBack",
    name: "Dos obsidienne",
    description: "Noir profond avec reflets acier.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#222936",
    rarity: "epic",
  },
  {
    id: "cards-aqua",
    category: "cardBack",
    name: "Dos aqua",
    description: "Cyan mineral au rendu plus lumineux.",
    price: SKIN_PRICES_BY_RARITY.legendary,
    preview: "#2a9db7",
    rarity: "legendary",
  },
  {
    id: "cards-linen",
    category: "cardBack",
    name: "Dos lin",
    description: "Fond clair avec motif discret.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#cbd7c0",
    rarity: "common",
  },
  {
    id: "cards-club",
    category: "cardBack",
    name: "Dos trefle",
    description: "Vert jeu de cartes avec marques sombres.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#3c8f67",
    rarity: "common",
  },
  {
    id: "cards-ruby",
    category: "cardBack",
    name: "Dos rubis",
    description: "Rouge profond inspire des tables privees.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#a83f4b",
    rarity: "rare",
  },
  {
    id: "cards-silver",
    category: "cardBack",
    name: "Dos argent",
    description: "Gris metallique avec liseres fins.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#9aa7b5",
    rarity: "rare",
  },
  {
    id: "roulette-ivory",
    category: "rouletteBall",
    name: "Bille ivoire",
    description: "La bille standard de roulette.",
    price: 0,
    preview: "#f9f7ef",
    rarity: "common",
  },
  {
    id: "roulette-sapphire",
    category: "rouletteBall",
    name: "Bille saphir",
    description: "Bleu clair avec reflet froid.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#7cc7ff",
    rarity: "common",
  },
  {
    id: "roulette-sun",
    category: "rouletteBall",
    name: "Bille solaire",
    description: "Jaune vif pour suivre la trajectoire.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#ffd166",
    rarity: "rare",
  },
  {
    id: "roulette-rose",
    category: "rouletteBall",
    name: "Bille rose",
    description: "Rose framboise tres visible sur la roue.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#ff8fb1",
    rarity: "rare",
  },
  {
    id: "roulette-jade",
    category: "rouletteBall",
    name: "Bille jade",
    description: "Vert profond avec une lueur nette.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#56d39a",
    rarity: "epic",
  },
  {
    id: "roulette-violet",
    category: "rouletteBall",
    name: "Bille violette",
    description: "Violet clair pour un contraste plus original.",
    price: SKIN_PRICES_BY_RARITY.legendary,
    preview: "#b58cff",
    rarity: "legendary",
  },
  {
    id: "roulette-pearl",
    category: "rouletteBall",
    name: "Bille perle",
    description: "Blanc nacre avec reflet doux.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#e8e2d5",
    rarity: "common",
  },
  {
    id: "roulette-copper",
    category: "rouletteBall",
    name: "Bille cuivre",
    description: "Teinte chaude au rendu casino classique.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#c57b57",
    rarity: "common",
  },
  {
    id: "roulette-azure",
    category: "rouletteBall",
    name: "Bille azur",
    description: "Bleu vif avec un contour clair.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#3aaeea",
    rarity: "rare",
  },
  {
    id: "roulette-eclipse",
    category: "rouletteBall",
    name: "Bille eclipse",
    description: "Noir brillant avec halo violet.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#5b4b8a",
    rarity: "epic",
  },
  {
    id: "rocket-classic",
    category: "rocketShip",
    name: "Fusee classique",
    description: "Lanceur arcade simple avec capsule arrondie.",
    price: 0,
    preview: "#f9f7ef",
    rarity: "common",
  },
  {
    id: "rocket-comet",
    category: "rocketShip",
    name: "Vaisseau spatial",
    description: "Navette futuriste avec ailes larges et cockpit lumineux.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#7cc7ff",
    rarity: "rare",
  },
  {
    id: "rocket-solar",
    category: "rocketShip",
    name: "Avion de chasse",
    description: "Jet rapide avec nez pointu et ailes tactiques.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#ffd166",
    rarity: "epic",
  },
  {
    id: "rocket-nebula",
    category: "rocketShip",
    name: "Fusee SpaceX",
    description: "Lanceur blanc et noir inspire des fusees modernes.",
    price: SKIN_PRICES_BY_RARITY.legendary,
    preview: "#f4f7fb",
    rarity: "legendary",
  },
  {
    id: "rocket-scout",
    category: "rocketShip",
    name: "Navette scout",
    description: "Petit vaisseau compact pour vols courts.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#b8c2bd",
    rarity: "common",
  },
  {
    id: "rocket-cargo",
    category: "rocketShip",
    name: "Cargo lunaire",
    description: "Module robuste avec silhouette large.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#bfa36f",
    rarity: "common",
  },
  {
    id: "rocket-redcap",
    category: "rocketShip",
    name: "Fusee rouge",
    description: "Fusee simple avec coiffe rouge arcade.",
    price: SKIN_PRICES_BY_RARITY.common,
    preview: "#ff6b6b",
    rarity: "common",
  },
  {
    id: "rocket-delta",
    category: "rocketShip",
    name: "Jet Delta",
    description: "Avion spatial triangulaire et nerveux.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#5eb8f1",
    rarity: "rare",
  },
  {
    id: "rocket-falcon",
    category: "rocketShip",
    name: "Faucon stellaire",
    description: "Chasseur spatial a ailes fines.",
    price: SKIN_PRICES_BY_RARITY.rare,
    preview: "#d5ddd9",
    rarity: "rare",
  },
  {
    id: "rocket-eclipse",
    category: "rocketShip",
    name: "Intercepteur eclipse",
    description: "Vaisseau sombre avec reacteurs bleus.",
    price: SKIN_PRICES_BY_RARITY.epic,
    preview: "#3b4a6b",
    rarity: "epic",
  },
  {
    id: "plinko-starfall",
    category: "plinkoBall",
    name: "Bille pluie d'etoiles",
    description: "Exclusif Nebula, scintillante comme une trainee cosmique.",
    price: 0,
    preview: "#b6e3ff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "plinko-aurora",
    category: "plinkoBall",
    name: "Bille aurore",
    description: "Exclusif Nebula, halo vert et bleu.",
    price: 0,
    preview: "#7df0c3",
    rarity: "epic",
    source: "special",
  },
  {
    id: "plinko-supernova",
    category: "plinkoBall",
    name: "Bille supernova",
    description: "Exclusif Nebula, coeur chaud et lumineux.",
    price: 0,
    preview: "#ffb86b",
    rarity: "epic",
    source: "special",
  },
  {
    id: "plinko-cosmic-ice",
    category: "plinkoBall",
    name: "Bille glace cosmique",
    description: "Exclusif Nebula, bleu froid cristallin.",
    price: 0,
    preview: "#aeefff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "plinko-galaxy-core",
    category: "plinkoBall",
    name: "Bille noyau galaxie",
    description: "Skin exclusif de coffre Nebula, avec coeur cosmique.",
    price: 0,
    preview: "#8fd3ff",
    rarity: "legendary",
    source: "special",
  },
  {
    id: "cards-joker-neon",
    category: "cardBack",
    name: "Dos joker neon",
    description: "Exclusif Royal, joker lumineux sur fond sombre.",
    price: 0,
    preview: "#79e29f",
    rarity: "epic",
    source: "special",
  },
  {
    id: "cards-crown-night",
    category: "cardBack",
    name: "Dos couronne nuit",
    description: "Exclusif Royal, couronne doree et bleu profond.",
    price: 0,
    preview: "#263a80",
    rarity: "epic",
    source: "special",
  },
  {
    id: "cards-gilded-mask",
    category: "cardBack",
    name: "Dos masque dore",
    description: "Exclusif Royal, masque de joker grave.",
    price: 0,
    preview: "#c58cff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "cards-ace-vault",
    category: "cardBack",
    name: "Dos as coffre",
    description: "Exclusif Royal, as scelle par des lignes dorees.",
    price: 0,
    preview: "#f5a95b",
    rarity: "epic",
    source: "special",
  },
  {
    id: "cards-joker-gold",
    category: "cardBack",
    name: "Dos joker dore",
    description: "Skin exclusif de coffre Royal, grave comme une carte joker premium.",
    price: 0,
    preview: "#ffd166",
    rarity: "legendary",
    source: "special",
  },
  {
    id: "roulette-opal",
    category: "rouletteBall",
    name: "Bille opale",
    description: "Exclusif Prism, reflets doux multicolores.",
    price: 0,
    preview: "#aeefff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "roulette-laser",
    category: "rouletteBall",
    name: "Bille laser",
    description: "Exclusif Prism, violet vif et halo net.",
    price: 0,
    preview: "#d86bff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "roulette-comet",
    category: "rouletteBall",
    name: "Bille comete",
    description: "Exclusif Prism, bleu rapide et lumineux.",
    price: 0,
    preview: "#5eb8f1",
    rarity: "epic",
    source: "special",
  },
  {
    id: "roulette-crystal",
    category: "rouletteBall",
    name: "Bille cristal",
    description: "Exclusif Prism, eclat clair et facette.",
    price: 0,
    preview: "#d8f3ff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "roulette-prism",
    category: "rouletteBall",
    name: "Bille prisme",
    description: "Skin exclusif de coffre Prism, avec reflets multicolores.",
    price: 0,
    preview: "#c58cff",
    rarity: "legendary",
    source: "special",
  },
  {
    id: "rocket-ion-wing",
    category: "rocketShip",
    name: "Aile ionique",
    description: "Exclusif Orbital, navette bleue a reacteurs fins.",
    price: 0,
    preview: "#8fd3ff",
    rarity: "epic",
    source: "special",
  },
  {
    id: "rocket-starlancer",
    category: "rocketShip",
    name: "Starlancer",
    description: "Exclusif Orbital, chasseur long et dore.",
    price: 0,
    preview: "#ffd166",
    rarity: "epic",
    source: "special",
  },
  {
    id: "rocket-blackbird",
    category: "rocketShip",
    name: "Blackbird orbital",
    description: "Exclusif Orbital, vaisseau noir furtif.",
    price: 0,
    preview: "#4d596b",
    rarity: "epic",
    source: "special",
  },
  {
    id: "rocket-capsule-v",
    category: "rocketShip",
    name: "Capsule V",
    description: "Exclusif Orbital, capsule verte haute vitesse.",
    price: 0,
    preview: "#79e29f",
    rarity: "epic",
    source: "special",
  },
  {
    id: "rocket-orbital-x",
    category: "rocketShip",
    name: "Vaisseau Orbital X",
    description: "Skin exclusif de coffre Orbital, profil de navette elite.",
    price: 0,
    preview: "#79e29f",
    rarity: "legendary",
    source: "special",
  },
];

export function buySkin(balance: number, ownedSkinIds: readonly string[], item: ShopItem) {
  if (balance < item.price) {
    return { balance, ownedSkinIds: [...ownedSkinIds], purchased: false, reason: "balance" as const };
  }

  return {
    balance: balance - item.price,
    ownedSkinIds: [...ownedSkinIds, item.id],
    purchased: true,
    reason: "ok" as const,
  };
}

export function equipSkin(equipped: EquippedSkins, item: ShopItem): EquippedSkins {
  return {
    ...equipped,
    [item.category]: item.id,
  };
}

export function getShopItem(id: string): ShopItem {
  const item = SHOP_ITEMS.find((candidate) => candidate.id === id);

  if (!item) {
    throw new Error(`Skin inconnu: ${id}`);
  }

  return item;
}
